# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_docker:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: "startsWith(github.event.head_commit.message, 'Build docker:')"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check Out Repo
        uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Define container info
        run: |
          echo "REPO: ${GITHUB_REPOSITORY}"
          SW_NAME=$(echo ${GITHUB_REPOSITORY##*/} | sed 's/ *$//g')
          echo "SW_NAME: ${SW_NAME}"
          DOCKER_SW_NAME=${SW_NAME,,}
          echo "DOCKER_SW_NAME: ${DOCKER_SW_NAME}"
          COMMIT_MESSAGE="${{ github.event.head_commit.message }}"
          echo "COMMIT_MESSAGE: ${COMMIT_MESSAGE}"
          SW_TAG=${COMMIT_MESSAGE#*"Build docker:"}
          echo "SW_TAG: ${SW_TAG}"
          SW_TAG=$(echo ${SW_TAG%%,*} | sed 's/ *$//g')
          echo "SW_TAG: ${SW_TAG}"
          DOCKERFILEPATH=$(find . -name "${SW_TAG}.dockerfile")
          echo "DOCKERFILEPATH: ${DOCKERFILEPATH}"
          CONTEXT_PATH=${DOCKERFILEPATH%/*}
          echo "CONTEXT_PATH: ${CONTEXT_PATH}"
          IMAGE_NAME="${DOCKER_ORG}/${DOCKER_SW_NAME}:${SW_TAG}"
          echo "IMAGE_NAME: ${IMAGE_NAME}"
          echo "CONTEXT_PATH=${CONTEXT_PATH}" >> $GITHUB_ENV
          echo "DOCKERFILE=${SW_TAG}.dockerfile" >> $GITHUB_ENV
          echo "IMAGE_NAME=${IMAGE_NAME}" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ${{ env.CONTEXT_PATH }}
          file: ${{ env.DOCKERFILE }}
          push: true
          tags: ${{ env.IMAGE_NAME }}
